### PR TITLE
Added security specification

### PR DESCRIPTION
**Pull request by kiancross**

### CODE REVIEW

**Comment by kiancross** [comment]
@chocol4te How can this be merged in? I don't usually use rebases, so not sure how to resolve the error :)

**Comment by chocol4te** [comment]
@chocol4te No worries, I'll resolve it now, not sure why the repo won't allow other kinds of merges though:/

**Comment by chocol4te** [comment]
@kiancross Resolved the conflicts and pushed to the `kiancross-security` branch, you can either merge that in, or force apply those changes to your fork's branch:)

**Comment by kiancross** [comment]
> No worries, I'll resolve it now, not sure why the repo won't allow other kinds of merges though:/

It's because they're disabled in the repo settings.

> Resolved the conflicts and pushed to the kiancross-security branch, you can either merge that in, or force apply those changes to your fork's branch:)

Thanks :)

**Comment by kiancross** [comment]
@chocol4te 

> not sure why the repo won't allow other kinds of merges though:/

Step 4 show show to change it: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuring-commit-squashing-for-pull-requests

#13 has the same problem too.

**Pull request merged**
