### PR TITLE
Added UserID to all requests

### PR DESCRIPTION
**Pull request by mmcilree**
(please check I have done this correctly - not very familiar with the format)

### CODE REVIEW

**Review by kiancross — CHANGES_REQUESTED** [review]

**Comment by kiancross** [comment]
This header field also needs adding to the security specification, as one of the included headers.

**Review by chocol4te — APPROVED** [review]
We should maybe see if it's possible to store the schema for a string with regex  `^[a-zA-Z0-9-_]{1,24}$` as a `$ref` but that's out of scope for this PR, LGTM:))

**Comment by kiancross** [comment]
Before this is merged in, the `User-ID` header needs adding to the list of headers in the security specification.

**Comment by chocol4te** [comment]
Blocked by #26

**Pull request merged**
