### PR TITLE
Change post content encoding

### PR DESCRIPTION
**Pull request by chocol4te**
* Removes `contentType`
* `content` is now an array of several different kinds of content objects

### CODE REVIEW

**Comment by chocol4te** [comment]
oh wait sorry some whitespace changes got added in, my bad

**Comment by kiancross** [comment]
@chocol4te I think we may have misunderstood each other slightly on Teams :) I was proposing that:

 - We keep the current `contentType` field but make it a string array only (rather than a string or string array).
 - Instead of merging all the `content` types into a single object (which is difficult for strongly typed projects), send each object separately in an array.
     * However, the concept that incompatible types should use conflicting fields remains.
     * For example, both the `text` and `markdown` `contentType` use the `text` property. This implicitly indicates that they cannot be used together and we do not have to maintain an explicit list of permissible permutations.

----

For example, suppose we have the following types:

```js
Markdown {
  text: string;
}
```
```js
Text {
  text: string;
}
```
```js
Poll {
  question: string;
  answers: string[];
}
```

Then a post containing a body of markdown, with a poll, would look like this:
```js
{
  ...
  contentType: ["markdown", "poll"],
  content: [
    {
      text: "Some markdown text"
    },
    {
      question: "Favourite animal?"
      answers: ["Dog", "Cat"]
    }
  ]
}
```

We can combine them because they do not have overlapping properties. What about if we try to combine `markdown` and `text`?

```js
{
  ...
  contentType: ["markdown", "text"],
  content: [
    {
      text: "Some markdown text"
    },
    {
      text: "Some normal text"
    }
  ]
}
```

We can validate each individual object (e.g. using a typed JSON library), and they're fine. However, we can see that the combination is invalid without explicitly storing which content types can be combined, simply by detecting that they have an overlapping field (in this case `text`).

What do you think?

**Comment by chocol4te** [comment]
I'm not sure how much I like having the two separate `content` and `contentType` fields, it seems to introduce additional complexity and validation steps when I'm not sure it's necessary. Namely the ordering of the two arrays must now be consistent (or at least specified to be inconsistent which doesn't seem nice). 

Including the type in the objects in the `content` array seems much easier:

```json
{
    "content": [
    {
        "markdown": {
            "text": "Some markdown text"
        }
    },
    {
        "poll": {
            "question": "Favourite animal?",
            "answers": ["Dog", "Cat"]
        }
    }
    ]
}
```

Incompatible combinations can still be described implicitly with the inner fields, though I accept because they are now nested that becomes more difficult. 

Though I was thinking about it and I'm really not sure that maintaining an explicit list of which types are mutually exclusive will be difficult, so far Markdown and Text seem to be the only ones. Just making it up off the top of my head if the valid types are Markdown, Text, Picture, Video, Poll, Link, Group Invitation, Assignment Submission, Livestream, the only two that we should be explicitly disallowing is Markdown and Text, for every other combination I can come up with a plausible scenario in which it would be needed.

I forget exactly the counterpoints to just having a single Text type in which markdown is supported, but if it is the only exception that requires checking for should we revisit the conversation?

**Comment by kiancross** [comment]
@chocol4te Most of these things probably won't have much of an impact either way, so happy to just keep a hardcoded list of incompatible types :)

> Including the type in the objects in the content array seems much easier

If doing it like this, I don't think it makes sense to send as an array anymore. In your example, I think the following would be better?

```json
{
    "content": {
        "markdown": {
            "text": "Some markdown text"
        },
        "poll": {
            "question": "Favourite animal?",
            "answers": ["Dog", "Cat"]
        }
    }
}
```

*If we add types such as `image` in the future, which could be included more than once, then that individual type can be an array.*

> I forget exactly the counterpoints to just having a single Text type in which markdown is supported, but if it is the only exception that requires checking for should we revisit the conversation?

My main objection to this is that the distinction between the two is easy enough to make and so we might as well. Rendering `markdown` as `text` is fine, but rendering `text` as `markdown` could cause problems. I suppose individual servers could treat them the same if they wish, but those who want to treat them individually have the option to.

**Comment by chocol4te** [comment]
@kiancross Thank you, I really appreciate it:)

Unfortunately it then makes it hard to have a concrete type for the content field if it can have any combination of fields within it, which is hard to provide a concrete type for. I think this also might make things easier because I can imagine wanting to post say several videos like a multi-part lecture, an image album, multiple submissions for an assignment etc.

> My main objection to this is that the distinction between the two is easy enough to make and so we might as well. Rendering markdown as text is fine, but rendering text as markdown could cause problems.

Oh right of course, makes sense:)

**Review by kiancross — APPROVED** [review]
> Unfortunately it then makes it hard to have a concrete type for the content field if it can have any combination of fields within it, which is hard to provide a concrete type for.

Ah right ok. In that case this all looks fine!

**Pull request merged**
