### PR TITLE
Fix author filter and add parentPost filter

### PR DESCRIPTION
**Pull request by chocol4te**

### CODE REVIEW

**Review by kiancross — APPROVED** [review]

**Comment by chocol4te** [comment]
@kiancross Due to the format of the author I'm assuming the correct response is to allow all hosts? I.E. posts by both `alice123@host1.com` and `alice123@host2.com` are returned when `?author=alice123` is given as a filter?

**Comment by kiancross** [comment]
@chocol4te Hmm good point. I think we need to specify the host, probably using the `@` notation?

Alternatively, we could remove the author filter from this endpoint and instead use the `/fed/users` (currently in a PR) endpoint for getting posts made by a user - this might make more sense as the user that a server belongs to knows about all the posts they have made.

**Comment by chocol4te** [comment]
@kiancross Personally I'd lean more towards the second option, just because introducing a second textual representation of users might lead to bugs and it seems to make more sense, but I'm totally open to either:)

**Comment by kiancross** [comment]
Yeah I prefer the second option too - I think there are more use cases for getting all the posts made by a user (i.e. for a profile page) rather than only the posts made to a particular server/community.

The second option can also be extended to add a `community` and `server` filter, if we wish.

**Comment by chocol4te** [comment]
@kiancross I'll make a PR removing the filter, is the end going to be something like `GET /fed/users/{id}/posts` or is someone already working on it?

**Comment by kiancross** [comment]
@chocol4te #11 adds a `/fed/users` endpoint. Once that is merged in we can build on top of it.

**Pull request merged**
