### PR TITLE
Deploy documentation with GitHub Actions

### PR DESCRIPTION
**Pull request by chocol4te**
This PR generates API documentation using [ReDoc](https://github.com/Redocly/redoc) and deploys to GitHub Pages at https://mckeogh.tech/cs3099a-specification/index.html.

### CODE REVIEW

**Comment by kiancross** [comment]
@chocol4te For PRs like #5, is it better if I move the markdown inside the yaml file so that it is included in the build? Or is there an alternative way to include external markdown files?

**Comment by chocol4te** [comment]
It looks like embedded external markdown is possible (https://redoc.ly/docs/api-reference-docs/embedded-markdown/), which do you think works better?

**Comment by kiancross** [comment]
I prefer the external markdown files as they're easier to edit using the GitHub interface. I'll give that a try later and see if it works - cheers.

**Comment by kiancross** [comment]
I can't see a way to add multiple markdown references to the main description. Is it possible to add additional sections that only consist of a `description`?

If not, we might just need to create a mega-markdown document which includes all the additional stuff, instead of separately (as in the PRs at the moment).

**Comment by kiancross** [comment]
@chocol4te You mentioned in today's meeting that you would validate the yaml. Could you just do a test build with redocly instead (and discard the output)?

**Comment by chocol4te** [comment]
@kiancross Additional sections with just a description seems possible, currently the WIP section is just the description (and should probably be removed)

I'm adding a commit now to make build the default step and only deploy on master

**Comment by kiancross** [comment]
> Additional sections with just a description seems possible, currently the WIP section is just the description (and should probably be removed)

Ah thanks - this looks like it will work. Submitted a PR in #14 to remove `extensions`.

**Pull request merged**
